In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Defining Vocabulary Size
voc_size = 10000

In [4]:
## One Hot Representation
one_hot_rep = [one_hot(words,voc_size) for words in sent]

In [5]:
one_hot_rep

[[9742, 4907, 4707, 1999],
 [9742, 4907, 4707, 354],
 [9742, 5783, 4707, 8606],
 [236, 5740, 8803, 8485, 9294],
 [236, 5740, 8803, 8485, 9780],
 [9817, 9742, 5590, 4707, 9920],
 [7517, 9871, 8916, 8485]]

In [6]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9742 4907 4707 1999]
 [   0    0    0    0 9742 4907 4707  354]
 [   0    0    0    0 9742 5783 4707 8606]
 [   0    0    0  236 5740 8803 8485 9294]
 [   0    0    0  236 5740 8803 8485 9780]
 [   0    0    0 9817 9742 5590 4707 9920]
 [   0    0    0    0 7517 9871 8916 8485]]


In [8]:
## Feature Representation (Word Embdedding)
dim = 10

In [9]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim))
model.compile('rmsprop', 'mse')

In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)